name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.x.x

    - name: Build F# project
      run: |
        dotnet restore FsFs.fsproj
        dotnet build FsFs.fsproj -c Release --no-restore